### ISSUE TITLE
What happened to this wonderful project?

### ISSUE THREAD

**Issue by q2dg** [lisa-project/lisa-user#101]
It seems pretty dead...
Do you know any current alternative, if so?
Thanks!!

**Comment by rrendec** [comment]
Unfortunately it _is_ pretty dead -- mostly due to lack of audience and/or users.

I would suggest to take a look at Open vSwitch (http://openvswitch.org/).

If you're interested in the switching itself (rather than the CLI) and don't use many vlans, a tandem of the _bridge_ and _8021q_ (standard) kernel modules could also be an option.

**Comment by q2dg** [comment]
Ah, ok! Thanks a lot for these suggestions! I'll look at them! Thanks!
