### ISSUE TITLE
Implement the userspace interface lists with the mm API

### ISSUE THREAD

**Issue by acrish** [lisa-project/lisa-user#3]
See README.mm and issue #6

**Comment by mihaelamartinas** [comment]
Sha for the commit: 271ec0094532fcc3fcaa75efb7d916d14c262e7f

**Comment by mihaelamartinas** [comment]
Commit: d38e7187e1ee656ab66b732719aac81ac04a36cf
I called the shared memory function to set interface description.
After looking in the in Cisco CLI, I put the default description for an interface to be "--" instead of "".

The link used for documentation:
http://www.cisco.com/en/US/docs/switches/datacenter/mds9000/sw/4_1/configuration/guides/cli_4_1/intf.html
